### ISSUE TITLE
ModuleNotFoundError: No module named 'signalfd._signalfd'

### ISSUE THREAD

**Issue by mgedmin** [ionelmc/python-signalfd#2]
Steps to reproduce:

```console
$ virtualenv /tmp/sandbox
created virtual environment CPython3.12.7.final.0-64 in 496ms

$ /tmp/sandbox/bin/pip install signalfd
Successfully installed cffi-1.17.1 pycparser-2.22 signalfd-0.4.0

$ /tmp/sandbox/bin/python
>>> import signalfd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/sandbox/lib/python3.12/site-packages/signalfd/__init__.py", line 8, in <module>
    from ._signalfd import ffi as _ffi
ModuleNotFoundError: No module named 'signalfd._signalfd'
```

I'm on Ubuntu 24.10.  I followed the installation instructions from https://python-signalfd.readthedocs.io/en/latest/installation.html.

**Comment by ionelmc** [comment]
That might have been some hidden build failure. I have done some update, can you retest?

**Comment by mgedmin** [comment]
Did a git pull, tried to `pip install .`, got this:

<details>

```console
$ /tmp/sandbox/bin/pip install .
Processing /home/mg/src/python-signalfd
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.0.0 in /tmp/sandbox/lib/python3.12/site-packages (from signalfd==0.4.0) (1.17.1)
Requirement already satisfied: pycparser in /tmp/sandbox/lib/python3.12/site-packages (from cffi>=1.0.0->signalfd==0.4.0) (2.22)
Building wheels for collected packages: signalfd
  Building wheel for signalfd (pyproject.toml) ... done
  Created wheel for signalfd: filename=signalfd-0.4.0-cp312-cp312-linux_x86_64.whl size=5184 sha256=79c5fd4def54f037b81334067f209a2ae7bf230d4dafea8174248c0f9da521b0
  Stored in directory: /home/mg/.cache/pip/wheels/15/a9/87/a02a3de2387fe10697b632ef14d42ef2261dee88c20d246e16
Successfully built signalfd
Installing collected packages: signalfd
  Attempting uninstall: signalfd
    Found existing installation: signalfd 0.4.0
    Uninstalling signalfd-0.4.0:
      Successfully uninstalled signalfd-0.4.0
Successfully installed signalfd-0.4.0
```

</details>

and

```console
$ /tmp/sandbox/bin/python 
Python 3.12.7 (main, Oct  3 2024, 15:15:22) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import signalfd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/sandbox/lib/python3.12/site-packages/signalfd/__init__.py", line 9, in <module>
    from ._signalfd import ffi as _ffi
ModuleNotFoundError: No module named 'signalfd._signalfd'
>>> 
```

The wheel file is missing the .so:

<details>

```
Archive:  /home/mg/.cache/pip/wheels/15/a9/87/a02a3de2387fe10697b632ef14d42ef2261dee88c20d246e16/signalfd-0.4.0-cp312-cp312-linux_x86_64.whl
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    2871  Defl:N      970  66% 2024-11-02 07:53 1e7749fb  signalfd/__init__.py
    2031  Defl:N      809  60% 2024-11-02 07:53 55e24922  signalfd/_signalfd_build.py
      69  Defl:N       65   6% 2024-11-02 07:53 6a23048e  signalfd-0.4.0.dist-info/AUTHORS.rst
    1329  Defl:N      713  46% 2024-11-02 07:53 c13bbdef  signalfd-0.4.0.dist-info/LICENSE
    2550  Defl:N      995  61% 2024-11-02 07:53 3c4cfe76  signalfd-0.4.0.dist-info/METADATA
     104  Defl:N      101   3% 2024-11-02 07:53 16d25943  signalfd-0.4.0.dist-info/WHEEL
       9  Defl:N       11 -22% 2024-11-02 07:53 e4d0aa06  signalfd-0.4.0.dist-info/top_level.txt
     643  Defl:N      396  38% 2024-11-02 07:53 e19c65da  signalfd-0.4.0.dist-info/RECORD
--------          -------  ---                            -------
    9606             4060  58%                            8 files
```

</details>

so why does the build not fail?

How do I convince pip to give me the full output of the build?

<details>
<summary>python -m build</summary>

``` console
$ uvx --from build python -m build
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - cffi>=1.0.0
  - setuptools>=30.3.0
* Getting build dependencies for sdist...
running egg_info
writing src/signalfd.egg-info/PKG-INFO
writing dependency_links to src/signalfd.egg-info/dependency_links.txt
writing requirements to src/signalfd.egg-info/requires.txt
writing top-level names to src/signalfd.egg-info/top_level.txt
reading manifest file 'src/signalfd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'AUTHORS.rst'
writing manifest file 'src/signalfd.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing src/signalfd.egg-info/PKG-INFO
writing dependency_links to src/signalfd.egg-info/dependency_links.txt
writing requirements to src/signalfd.egg-info/requires.txt
writing top-level names to src/signalfd.egg-info/top_level.txt
reading manifest file 'src/signalfd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'AUTHORS.rst'
writing manifest file 'src/signalfd.egg-info/SOURCES.txt'
running check
creating signalfd-0.4.0
creating signalfd-0.4.0/.github/workflows
creating signalfd-0.4.0/ci
creating signalfd-0.4.0/ci/templates/.github/workflows
creating signalfd-0.4.0/docs
creating signalfd-0.4.0/docs/reference
creating signalfd-0.4.0/src/signalfd
creating signalfd-0.4.0/src/signalfd.egg-info
creating signalfd-0.4.0/tests
copying files to signalfd-0.4.0...
copying .bumpversion.cfg -> signalfd-0.4.0
copying .cookiecutterrc -> signalfd-0.4.0
copying .coveragerc -> signalfd-0.4.0
copying .editorconfig -> signalfd-0.4.0
copying .pre-commit-config.yaml -> signalfd-0.4.0
copying .readthedocs.yml -> signalfd-0.4.0
copying AUTHORS.rst -> signalfd-0.4.0
copying CHANGELOG.rst -> signalfd-0.4.0
copying CONTRIBUTING.rst -> signalfd-0.4.0
copying LICENSE -> signalfd-0.4.0
copying MANIFEST.in -> signalfd-0.4.0
copying README.rst -> signalfd-0.4.0
copying pyproject.toml -> signalfd-0.4.0
copying pytest.ini -> signalfd-0.4.0
copying setup.py -> signalfd-0.4.0
copying tox.ini -> signalfd-0.4.0
copying .github/workflows/github-actions.yml -> signalfd-0.4.0/.github/workflows
copying ci/bootstrap.py -> signalfd-0.4.0/ci
copying ci/requirements.txt -> signalfd-0.4.0/ci
copying ci/templates/.github/workflows/github-actions.yml -> signalfd-0.4.0/ci/templates/.github/workflows
copying docs/authors.rst -> signalfd-0.4.0/docs
copying docs/changelog.rst -> signalfd-0.4.0/docs
copying docs/conf.py -> signalfd-0.4.0/docs
copying docs/contributing.rst -> signalfd-0.4.0/docs
copying docs/index.rst -> signalfd-0.4.0/docs
copying docs/installation.rst -> signalfd-0.4.0/docs
copying docs/readme.rst -> signalfd-0.4.0/docs
copying docs/requirements.txt -> signalfd-0.4.0/docs
copying docs/spelling_wordlist.txt -> signalfd-0.4.0/docs
copying docs/usage.rst -> signalfd-0.4.0/docs
copying docs/reference/index.rst -> signalfd-0.4.0/docs/reference
copying docs/reference/signalfd.rst -> signalfd-0.4.0/docs/reference
copying src/signalfd/__init__.py -> signalfd-0.4.0/src/signalfd
copying src/signalfd/_signalfd_build.py -> signalfd-0.4.0/src/signalfd
copying src/signalfd.egg-info/PKG-INFO -> signalfd-0.4.0/src/signalfd.egg-info
copying src/signalfd.egg-info/SOURCES.txt -> signalfd-0.4.0/src/signalfd.egg-info
copying src/signalfd.egg-info/dependency_links.txt -> signalfd-0.4.0/src/signalfd.egg-info
copying src/signalfd.egg-info/not-zip-safe -> signalfd-0.4.0/src/signalfd.egg-info
copying src/signalfd.egg-info/requires.txt -> signalfd-0.4.0/src/signalfd.egg-info
copying src/signalfd.egg-info/top_level.txt -> signalfd-0.4.0/src/signalfd.egg-info
copying tests/test_signalfd.py -> signalfd-0.4.0/tests
copying tests/test_sigprocmask.py -> signalfd-0.4.0/tests
copying src/signalfd.egg-info/SOURCES.txt -> signalfd-0.4.0/src/signalfd.egg-info
Writing signalfd-0.4.0/setup.cfg
Creating tar archive
removing 'signalfd-0.4.0' (and everything under it)
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - cffi>=1.0.0
  - setuptools>=30.3.0
* Getting build dependencies for wheel...
running egg_info
writing src/signalfd.egg-info/PKG-INFO
writing dependency_links to src/signalfd.egg-info/dependency_links.txt
writing requirements to src/signalfd.egg-info/requires.txt
writing top-level names to src/signalfd.egg-info/top_level.txt
reading manifest file 'src/signalfd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'AUTHORS.rst'
writing manifest file 'src/signalfd.egg-info/SOURCES.txt'
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/signalfd
copying src/signalfd/__init__.py -> build/lib.linux-x86_64-cpython-312/signalfd
copying src/signalfd/_signalfd_build.py -> build/lib.linux-x86_64-cpython-312/signalfd
running egg_info
writing src/signalfd.egg-info/PKG-INFO
writing dependency_links to src/signalfd.egg-info/dependency_links.txt
writing requirements to src/signalfd.egg-info/requires.txt
writing top-level names to src/signalfd.egg-info/top_level.txt
reading manifest file 'src/signalfd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'AUTHORS.rst'
writing manifest file 'src/signalfd.egg-info/SOURCES.txt'
running build_ext
generating cffi module 'build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c'
creating build/temp.linux-x86_64-cpython-312
building 'signalfd._signalfd' extension
creating build/temp.linux-x86_64-cpython-312/build/temp.linux-x86_64-cpython-312
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/tmp/build-env-8w7tt2bh/include -I/usr/include/python3.12 -c build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c -o build/temp.linux-x86_64-cpython-312/build/temp.linux-x86_64-cpython-312/signalfd._signalfd.o
build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c: In function ‘_cffi_checkfld_typedef_sigset_t’:
build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c:618:33: error: initialization of ‘long unsigned int (*)[1024]’ from incompatible pointer type ‘long unsigned int (*)[16]’ [-Wincompatible-pointer-types]
  618 |   { unsigned long(*tmp)[1024] = &p->__val; (void)tmp; }
      |                                 ^
********************************************************************************
WARNING:

    An optional code optimization (C extension) could not be compiled.

    Optimizations for this package will not be available!
            
CAUSE:

    CompileError(DistutilsExecError("command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1"))
********************************************************************************
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/signalfd
copying build/lib.linux-x86_64-cpython-312/signalfd/__init__.py -> build/bdist.linux-x86_64/wheel/./signalfd
copying build/lib.linux-x86_64-cpython-312/signalfd/_signalfd_build.py -> build/bdist.linux-x86_64/wheel/./signalfd
running install_egg_info
Copying src/signalfd.egg-info to build/bdist.linux-x86_64/wheel/./signalfd-0.4.0-py3.12.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/signalfd-0.4.0.dist-info/WHEEL
creating '/home/mg/src/python-signalfd/dist/.tmp-sd8z4is8/signalfd-0.4.0-cp312-cp312-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'signalfd/__init__.py'
adding 'signalfd/_signalfd_build.py'
adding 'signalfd-0.4.0.dist-info/AUTHORS.rst'
adding 'signalfd-0.4.0.dist-info/LICENSE'
adding 'signalfd-0.4.0.dist-info/METADATA'
adding 'signalfd-0.4.0.dist-info/WHEEL'
adding 'signalfd-0.4.0.dist-info/top_level.txt'
adding 'signalfd-0.4.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built signalfd-0.4.0.tar.gz and signalfd-0.4.0-cp312-cp312-linux_x86_64.whl
```

</details>

The highlights:

```
build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c: In function ‘_cffi_checkfld_typedef_sigset_t’:
build/temp.linux-x86_64-cpython-312/signalfd._signalfd.c:618:33: error: initialization of ‘long unsigned int (*)[1024]’ from incompatible pointer type ‘long unsigned int (*)[16]’ [-Wincompatible-pointer-types]
  618 |   { unsigned long(*tmp)[1024] = &p->__val; (void)tmp; }
      |                                 ^
********************************************************************************
WARNING:

    An optional code optimization (C extension) could not be compiled.

    Optimizations for this package will not be available!
            
CAUSE:

    CompileError(DistutilsExecError("command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1"))
```

Two things:

- Ubuntu 24.10 has a newer GCC version which is more strict about pointer type casting
- for some reason your `setup.py` is intentionally making distutils/setuptools treat build failures as acceptable and proceed without the .so file

**Comment by ionelmc** [comment]
It's released now.

**Comment by mgedmin** [comment]
Thank you!
